name: mbiomekit
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - setuptools
  - pytest
  - scikit-learn 
  - scikit-posthocs
  - pip
  - pip:
    - -e .
